In [1]:
from sentence_transformers import SentenceTransformer, util
# util.pytorch_cos_sim(embeddings[i], embeddings[j]).item())
# sentences = ["This is an example sentence", "Each sentence is converted"]

# t5_bert_model = SentenceTransformer('sentence-transformers/sentence-t5-base')
# t5_bert_model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
# t5_bert_model = SentenceTransformer('stsb-roberta-large')
t5_bert_model = SentenceTransformer('sentence-transformers/msmarco-bert-base-dot-v5')


# embeddings = model.encode(sentences)
# print(embeddings)

2023-01-06 17:03:22.889100: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-06 17:03:24.568211: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-06 17:03:24.568405: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-06 17:03:24.568428: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nv

In [10]:
sentences = class_attempt[0].extend(twitter_df[twitter_df['label']=='Attempt'].values.tolist())
embeddings = t5_bert_model.encode(sentences, convert_to_tensor=True)

similarity = []
for i in range(len(sentences)):
    row = []
    for j in range(len(sentences)):
        row.append(util.pytorch_cos_sim(embeddings[i], embeddings[j]).item())
        time.sleep(2)
    tile.sleep(2)
    similarity.append(row)

TypeError: 'NoneType' object is not subscriptable

In [2]:
def get_embeddings(model, text_data):
    return model.encode([text_data])

In [12]:
import time

In [13]:
CSSR_CAT = ['Indicator', 'Attempt','Behavior','Ideation', 'Supportive']
output = dict.fromkeys(CSSR_CAT)

all_score = []
for i in CSSR_CAT:
    reddit_df = class_dataframe[class_dataframe['label']==i]
    reddit_df.reset_index(inplace=True, drop=True)
    reddit_data = ' '.join(reddit_df['text'].values.tolist())
    reddit_embedding = get_embeddings(t5_bert_model, reddit_data)
    
    compare_score = []
    i=1
    for _, j in twitter_df.iterrows():
        twitter_embedding = get_embeddings(t5_bert_model, j['text'])
        compare_score.append(linear_kernel(reddit_embedding, twitter_embedding))
        if i > 5:
            break
        i+=1
    time.sleep(3)
    all_score.append(sum(compare_score)/i)

In [14]:
all_score

[array([[200.5308]], dtype=float32),
 array([[203.47261]], dtype=float32),
 array([[201.56844]], dtype=float32),
 array([[199.58858]], dtype=float32),
 array([[197.9092]], dtype=float32)]

In [10]:
all_score

[array([[0.58524317]], dtype=float32),
 array([[0.58334]], dtype=float32),
 array([[0.6497788]], dtype=float32),
 array([[0.64655393]], dtype=float32),
 array([[0.48477268]], dtype=float32)]

In [12]:
np.sum(np.array(all_score))/len(all_score)

0.5899377346038819

### Gensim w2v model

In [ ]:
from gensim.models.keyedvectors import load_word2vec_format

In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import linear_kernel

In [3]:
from ipynb.fs.full.preprocess_and_generate_dataset import generate_dataframe

In [4]:
class_dataframe = generate_dataframe(10)
class_dataframe = class_dataframe.rename(columns={'Post': 'text', 'Label':'label'})


In [5]:
class_dataframe

text       label  code
0   viable option youll leaving wife behind youd p...  Supportive     4
1   hard appreciate notion could meet someone else...    Ideation     2
2   hi last night wa sitting ledge window contempl...    Behavior     1
3   tried kill self failed badly cause moment want...     Attempt     0
4   hi nem3030 sort thing enjoy personally always ...    Ideation     2
..                                                ...         ...   ...
30   Organic mood affective disorders Hypomania Re...    Ideation     2
47   Gender identity disorder of adolescence.3 pre...   Indicator     3
76   Intertrigo of abdominal skin fold Early yaws ...   Indicator     3
82   Parasitic skin infestation Foreign body granu...   Indicator     3
13    Changing normal routine Loss of appetite Poo...    Behavior     1

[730 rows x 3 columns]

In [8]:
class_attempt = class_dataframe[class_dataframe['label']=='Attempt'].values.tolist()

In [83]:
model_file = '/home/ifte-home/work/resources/w2v_300/model.bin'
dimention = 300

In [84]:
model = load_word2vec_format(model_file, binary=True, unicode_errors='ignore')

In [10]:
df = pd.read_csv('/home/ifte-home/Documents/mental_health/suicide/CSSRS/TFIDF_result_suicide_intensity.csv', index_col=0)
twitter_df = df
twitter_df

text       label
69567  time read format wanted make book could done j...   Indicator
5571   depressed year story hope help raise awareness...   Indicator
34978  long text friend doubt anyone read tldr highly...   Indicator
28886  fuck idek name call badger year canadian dont ...   Indicator
87420  pickle pickle existence girl matter born write...   Indicator
...                                                  ...         ...
41618  hentai helped become simp warning loooong text...  Supportive
31865  anyone need reason live would miss worth alive...  Supportive
14780  stressing life frankly sick tired world someti...  Supportive
40249  last advice offer make mistake often severe ot...  Supportive
69718  faking someone else front people guess would w...  Supportive

[500 rows x 2 columns]

text       label
69567  time read format wanted make book could done j...   Indicator
5571   depressed year story hope help raise awareness...   Indicator
34978  long text friend doubt anyone read tldr highly...   Indicator
28886  fuck idek name call badger year canadian dont ...   Indicator
87420  pickle pickle existence girl matter born write...   Indicator
...                                                  ...         ...
41618  hentai helped become simp warning loooong text...  Supportive
31865  anyone need reason live would miss worth alive...  Supportive
14780  stressing life frankly sick tired world someti...  Supportive
40249  last advice offer make mistake often severe ot...  Supportive
69718  faking someone else front people guess would w...  Supportive

[500 rows x 2 columns]

In [7]:
twitter_df.label.value_counts()

Indicator     100
Attempt       100
Behavior      100
Ideation      100
Supportive    100
Name: label, dtype: int64

In [87]:
def get_vector(text, dimention):
    sum_vec = np.zeros(dimention)
    word_count = 0
    for items in text.split():
        try: 
            temp = model[items]
        except KeyError:
            temp = 0
        sum_vec += temp
        word_count += 1
    return sum_vec / word_count


In [88]:
def train_dataset(dataset, dim):
    vector_collection = []
    for i, col in dataset.iterrows():
        vector_collection.append(get_vector(col['text'], dim))
    return np.array(vector_collection)

vector_collection_twitter = train_dataset(twitter_df, dimention)

In [94]:
def get_avg_simiarity(reddit_string, dimention, twitter_vector):
    reddit_vector = get_vector(reddit_string, dimention).reshape(1,-1)
    rank = linear_kernel(reddit_vector, twitter_vector)
    cosine_similarities = rank.flatten()
    ranked_index = cosine_similarities.argsort()[:-100:-1]    
#     print(related_docs)
    output = cosine_similarities[ranked_index]
    avg_result = np.sum(output)/ranked_index.size
    return avg_result, ranked_index

In [90]:
CSSR_CAT = ['Indicator', 'Attempt','Behavior','Ideation', 'Supportive']
output = dict.fromkeys(CSSR_CAT)

best_df = pd.DataFrame()
for i in CSSR_CAT:
    reddit_df = class_dataframe[class_dataframe['label']==i]
    reddit_df.reset_index(inplace=True, drop=True)
    reddit_compare = ' '.join(reddit_df['text'].values.tolist())
    
    temp, best_indices = get_avg_simiarity(reddit_compare, dimention, vector_collection_twitter)
    output[i] = temp
    
    new_df = df.iloc[best_indices[:100]]
    new_df['label_w2v'] = i
    best_df = pd.concat([best_df, new_df])
#     break

In [98]:
output

{'Indicator': 0.22288251827977282,
 'Attempt': 0.22585436680061988,
 'Behavior': 0.23246457221659597,
 'Ideation': 0.2323778402409954,
 'Supportive': 0.24041617908844734}

In [93]:
df

text       label
69567  time read format wanted make book could done j...   Indicator
5571   depressed year story hope help raise awareness...   Indicator
34978  long text friend doubt anyone read tldr highly...   Indicator
28886  fuck idek name call badger year canadian dont ...   Indicator
87420  pickle pickle existence girl matter born write...   Indicator
...                                                  ...         ...
41618  hentai helped become simp warning loooong text...  Supportive
31865  anyone need reason live would miss worth alive...  Supportive
14780  stressing life frankly sick tired world someti...  Supportive
40249  last advice offer make mistake often severe ot...  Supportive
69718  faking someone else front people guess would w...  Supportive

[500 rows x 2 columns]

In [ ]:
import fasttext
import io

def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = map(float, tokens[1:])
    return data

vectors = load_vectors('/home/ifte-home/work/resources/crawl-300d-2M.vec')
model = fasttext.load_model(vectors)